# Generated by Django 4.1.7 on 2023-03-17 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('Tank', 'Танк'), ('Healer', 'Хил'), ('DD', 'ДД'), ('Trader', 'Торговец'), ('GM', 'Гильдмастер'), ('QG', 'Квестгивер'), ('BLACKSMITH', 'Кузнец'), ('Tanner', 'Кожевник'), ('Potions master', 'Зельевар'), ('Spell master', 'Мастер заклинаний')], max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('response', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.advertisement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.author')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.author'),
        ),
    ]
