# Generated by Django 4.1.7 on 2023-03-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='response',
        ),
    ]
